version: '3.7'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: app_store_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379