spring:
  datasource:
    username: ${DB_USER:username}
    password: ${DB_PASS:password}
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:app_store_db}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimumIdle: ${HIKARI_MIN_IDLE:3}
      maximumPoolSize: ${HIKARI_MAX_POOL_SIZE:50}
      idleTimeout: ${HIKARI_IDLE_TIMEOUT:60000}
      maxLifetime: ${HIKARI_MAX_LIFE_TIME:66000}
      connectionTimeout: ${HIKARI_CONN_TIMEOUT:5000}
  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
